replicaCount: 1

image:
  repository: 175321200489.dkr.ecr.ap-northeast-2.amazonaws.com/spring-petclinic-customers-service
  tag: latest
  pullPolicy: Always

database:
  url: jdbc:mysql://petclinic-db-dev.ccitclnvbmiv.ap-northeast-2.rds.amazonaws.com:3306/customers_db
  username: admin
  passwordSecret: db-secret
  passwordKey: password
